### ISSUE TITLE
Session persistance

### ISSUE THREAD

**Issue by jaakkokorhonen** [d-cent/stonecutter#5]
When logging in, after leaving the page, it asks login info again. Maybe a cookie to make sessions persistent, would be in place?

**Comment by Seraphiana** [comment]
I'm not sure I understand what you mean by this? As in, if enter your details and then don't submit the form it should remember them?

Login credentials are stored temporarily, is it possible your login timed out?

**Comment by jaakkokorhonen** [comment]
ok i will test again

**Comment by jaakkokorhonen** [comment]
Ups  https://sso.dcentproject.eu/ says Server not found.

**Comment by jaakkokorhonen** [comment]
ok right, the server was not available there in between, so probably just a hickup.
